// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXeWug-060t_nZ9dpW0urwIRrW1cuyRE',
    appId: '1:898273018789:android:f7ad3c8fbc8bbf5467de4c',
    messagingSenderId: '898273018789',
    projectId: 'gettheskydoctor',
    storageBucket: 'gettheskydoctor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtCnLrwLosw_tf0LoqLcQSmtTjTHjoW38',
    appId: '1:898273018789:ios:4ece3d84e597a80f67de4c',
    messagingSenderId: '898273018789',
    projectId: 'gettheskydoctor',
    storageBucket: 'gettheskydoctor.appspot.com',
    androidClientId: '898273018789-veo6njsp2465u71j6l5kfe29rde1tnkh.apps.googleusercontent.com',
    iosClientId: '898273018789-bv01ujp5gurhqidf4lul2bfvcm901g3j.apps.googleusercontent.com',
    iosBundleId: 'com.gettheskydoctors.patient',
  );
}
