#Flutter Wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-keep class io.agora.**{*;}
-keep class io.agora.** {*;}
-dontwarn  io.agora.**
-keep class com.hyphenate.** {*;}
-dontwarn  com.hyphenate.**